apiVersion: v1
items:
  - apiVersion: image.openshift.io/v1
    kind: ImageStream
    metadata:
      generation: 1
      labels:
        app: go-simple-service
      name: go-simple-service
    spec:
      lookupPolicy:
        local: false
  - apiVersion: build.openshift.io/v1
    kind: BuildConfig
    metadata:
      labels:
        app: go-simple-service
      name: go-simple-service
    spec:
      failedBuildsHistoryLimit: 5
      nodeSelector: null
      output:
        to:
          kind: ImageStreamTag
          name: go-simple-service:latest
      postCommit: {}
      resources: {}
      runPolicy: Serial
      source:
        dockerfile: |-
          FROM adoptopenjdk/openjdk11:alpine-slim as builder

          WORKDIR /app
          COPY . .
          RUN ./mvnw clean package -DskipTests -P openshift

          FROM adoptopenjdk/openjdk11:alpine-jre
          RUN apk add --no-cache curl
          RUN curl -fsSLk https://github.com/stedolan/jq/releases/download/jq-1.6/jq-linux64 -o /usr/local/bin/jq
          RUN chmod a+x /usr/local/bin/jq
          COPY --from=builder /app/target/application.jar /
          ENTRYPOINT ["java","-Djava.security.egd=file:/dev/./urandom","-jar","/application.jar"]
        git:
          ref: master
          uri: https://github.com/in-the-keyhole/go-simple-service.git
        type: Git
      strategy:
        dockerStrategy:
          noCache: true
        type: Docker
      successfulBuildsHistoryLimit: 5
      triggers: []
  - apiVersion: v1
    kind: BuildConfig
    metadata:
      labels:
        app: go-simple-service
      name: go-simple-service-pipeline
      annotations:
        pipeline.alpha.openshift.io/uses:
          [
            {
              "name": "go-simple-service",
              "namespace": "",
              "kind": "DeploymentConfig",
            },
          ]
    spec:
      failedBuildsHistoryLimit: 5
      nodeSelector: null
      output: {}
      postCommit: {}
      resources: {}
      runPolicy: Serial
      source:
        git:
          ref: master
          uri: https://github.com/in-the-keyhole/go-simple-service.git
        sourceSecret:
          name: git-credentials
        type: Git
      strategy:
        jenkinsPipelineStrategy:
          jenkinsfile: >
            pipeline {
              agent { node { label 'maven' } }
              stages {
                stage('Fetch Source') {
                  steps {
                    git url: 'https://github.com/in-the-keyhole/go-simple-service.git', branch: 'master'
                  }
                }
                
                stage('Unit Testing') {
                  steps {
                    sh("./mvnw clean test")
                  }
                }

                stage('Build Image') {
                  steps {
                    script {
                      openshift.withCluster() {
                        openshift.withProject("development") {
                          openshift.selector("bc", "go-simple-service").startBuild("--wait")
                        }
                      }
                    }
                  }
                }

                stage('Deploy') {
                  steps {
                    script {
                      openshift.withCluster() {
                        openshift.withProject("development") {
                          def dc = openshift.selector("dc", "go-simple-service")
                          def rm = dc.rollout().latest()
                          dc.rollout().status()
                        }
                      }
                    }
                  }
                }
              }
            }
        type: JenkinsPipeline
      successfulBuildsHistoryLimit: 5
      triggers:
        - github:
            secretReference:
              name: github
          type: GitHub
  - apiVersion: apps.openshift.io/v1
    kind: DeploymentConfig
    metadata:
      labels:
        app: go-simple-service
      name: go-simple-service
    spec:
      replicas: 1
      revisionHistoryLimit: 10
      selector:
        deploymentconfig: go-simple-service
      strategy:
        activeDeadlineSeconds: 21600
        resources: {}
        rollingParams:
          intervalSeconds: 1
          maxSurge: 25%
          maxUnavailable: 25%
          timeoutSeconds: 600
          updatePeriodSeconds: 1
        type: Rolling
      template:
        metadata:
          labels:
            app: go-simple-service
            deploymentconfig: go-simple-service
        spec:
          containers:
            - env:
                - name: JAVA_OPTS
                  value: -Xss256K -Xms16M -Xmx32M
              image: go-simple-service:latest
              imagePullPolicy: Always
              name: go-simple-service
              ports:
                - containerPort: 8080
                  protocol: TCP
              resources: {}
              terminationMessagePath: /dev/termination-log
              terminationMessagePolicy: File
          dnsPolicy: ClusterFirst
          restartPolicy: Always
          schedulerName: default-scheduler
          securityContext: {}
          terminationGracePeriodSeconds: 30
      test: false
      triggers:
        - imageChangeParams:
            containerNames:
              - go-simple-service
            from:
              kind: ImageStreamTag
              name: go-simple-service:latest
          type: ImageChange
  - apiVersion: v1
    kind: Service
    metadata:
      labels:
        app: go-simple-service
      name: go-simple-service
    spec:
      ports:
        - name: 8080-tcp
          port: 8080
          protocol: TCP
          targetPort: 8080
      selector:
        deploymentconfig: go-simple-service
      sessionAffinity: None
      type: ClusterIP
  - apiVersion: route.openshift.io/v1
    kind: Route
    metadata:
      labels:
        app: go-simple-service
      name: go-simple-service
    spec:
      port:
        targetPort: 8080-tcp
      subdomain: ""
      tls:
        insecureEdgeTerminationPolicy: None
        termination: edge
      to:
        kind: Service
        name: go-simple-service
        weight: 100
      wildcardPolicy: None
kind: List
metadata:
  resourceVersion: ""
  selfLink: ""
