apiVersion: v1
items:
  # IMAGE STREAM
  - apiVersion: image.openshift.io/v1
    kind: ImageStream
    metadata:
      generation: 1
      labels:
        app: simple-go-service
      name: simple-go-service
    spec:
      lookupPolicy:
        local: false
  # BUILD CONFIG
  - apiVersion: build.openshift.io/v1
    kind: BuildConfig
    metadata:
      labels:
        app: simple-go-service
      name: simple-go-service
    spec:
      failedBuildsHistoryLimit: 5
      nodeSelector: null
      output:
        to:
          kind: ImageStreamTag
          name: simple-go-service:latest
      postCommit: {}
      resources: {}
      runPolicy: Serial
      source:
        dockerfile: |-
          FROM golang:alpine AS build-env
          RUN apk --no-cache add build-base git bzr mercurial gcc
          ADD . /src
          RUN cd /src && go build -o simple-go-service

          # final stage
          FROM alpine
          WORKDIR /app
          COPY --from=build-env /src/simple-go-service /app/
          ENTRYPOINT ./simple-go-service
        git:
          ref: master
          uri: https://github.com/in-the-keyhole/simple-go-service.git
        type: Git
      strategy:
        dockerStrategy:
          noCache: true
        type: Docker
      successfulBuildsHistoryLimit: 5
      triggers: []
  # PIPELINE
  - apiVersion: v1
    kind: BuildConfig
    metadata:
      labels:
        app: simple-go-service
      name: simple-go-service-pipeline
      annotations:
        pipeline.alpha.openshift.io/uses:
          [
            {
              "name": "simple-go-service",
              "namespace": "",
              "kind": "DeploymentConfig",
            },
          ]
    spec:
      failedBuildsHistoryLimit: 5
      nodeSelector: null
      output: {}
      postCommit: {}
      resources: {}
      runPolicy: Serial
      source:
        git:
          ref: master
          uri: https://github.com/in-the-keyhole/simple-go-service.git
        sourceSecret:
          name: git-credentials
        type: Git
      strategy:
        jenkinsPipelineStrategy:
          jenkinsfile: >
            pipeline {
              agent { node { label 'maven' } }
              stages {

                stage('Build Image') {
                  steps {
                    script {
                      openshift.withCluster() {
                        openshift.withProject("development") {
                          openshift.selector("bc", "simple-go-service").startBuild("--wait")
                        }
                      }
                    }
                  }
                }

                stage('Deploy') {
                  steps {
                    script {
                      openshift.withCluster() {
                        openshift.withProject("development") {
                          def dc = openshift.selector("dc", "simple-go-service")
                          def rm = dc.rollout().latest()
                          dc.rollout().status()
                        }
                      }
                    }
                  }
                }
              }
            }
        type: JenkinsPipeline
      successfulBuildsHistoryLimit: 5
      triggers:
        - github:
            secretReference:
              name: github
          type: GitHub
  # DEPLOYMENT CONFIG
  - apiVersion: apps.openshift.io/v1
    kind: DeploymentConfig
    metadata:
      labels:
        app: simple-go-service
      name: simple-go-service
    spec:
      replicas: 1
      revisionHistoryLimit: 10
      selector:
        deploymentconfig: simple-go-service
      strategy:
        activeDeadlineSeconds: 21600
        resources: {}
        rollingParams:
          intervalSeconds: 1
          maxSurge: 25%
          maxUnavailable: 25%
          timeoutSeconds: 600
          updatePeriodSeconds: 1
        type: Rolling
      template:
        metadata:
          labels:
            app: simple-go-service
            deploymentconfig: simple-go-service
        spec:
          containers:
            - env:
                - name: JAVA_OPTS
                  value: -Xss256K -Xms16M -Xmx32M
              image: simple-go-service:latest
              imagePullPolicy: Always
              name: simple-go-service
              ports:
                - containerPort: 8080
                  protocol: TCP
              readinessProbe:
                tcpSocket:
                  port: 8080
                initialDelaySeconds: 5
                periodSeconds: 10
              livenessProbe:
                tcpSocket:
                  port: 8080
                initialDelaySeconds: 15
                periodSeconds: 20
              resources: {}
              terminationMessagePath: /dev/termination-log
              terminationMessagePolicy: File
          dnsPolicy: ClusterFirst
          restartPolicy: Always
          schedulerName: default-scheduler
          securityContext: {}
          terminationGracePeriodSeconds: 30
      test: false
      triggers:
        - imageChangeParams:
            containerNames:
              - simple-go-service
            from:
              kind: ImageStreamTag
              name: simple-go-service:latest
          type: ImageChange
  # SERVICE
  - apiVersion: v1
    kind: Service
    metadata:
      labels:
        app: simple-go-service
      name: simple-go-service
    spec:
      ports:
        - name: 8080-tcp
          port: 8080
          protocol: TCP
          targetPort: 8080
      selector:
        deploymentconfig: simple-go-service
      sessionAffinity: None
      type: ClusterIP
  # ROUTE
  - apiVersion: route.openshift.io/v1
    kind: Route
    metadata:
      labels:
        app: simple-go-service
      name: simple-go-service
    spec:
      port:
        targetPort: 8080-tcp
      subdomain: ""
      tls:
        insecureEdgeTerminationPolicy: None
        termination: edge
      to:
        kind: Service
        name: simple-go-service
        weight: 100
      wildcardPolicy: None
kind: List
metadata:
  resourceVersion: ""
  selfLink: ""
